# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\atree\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shp-feature-selector\ui\input_layer_selector.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_input_selector_form(object):
    def setupUi(self, input_selector_form):
        input_selector_form.setObjectName("input_selector_form")
        input_selector_form.resize(291, 67)
        self.selector_widget = QtWidgets.QWidget(input_selector_form)
        self.selector_widget.setGeometry(QtCore.QRect(9, 9, 273, 49))
        self.selector_widget.setObjectName("selector_widget")
        self.layoutWidget = QtWidgets.QWidget(self.selector_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.input_selector_hlayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.input_selector_hlayout.setContentsMargins(0, 0, 0, 0)
        self.input_selector_hlayout.setObjectName("input_selector_hlayout")
        self.input_layer_label = QtWidgets.QLabel(self.layoutWidget)
        self.input_layer_label.setObjectName("input_layer_label")
        self.input_selector_hlayout.addWidget(self.input_layer_label)
        self.input_layer_dd = QtWidgets.QComboBox(self.layoutWidget)
        self.input_layer_dd.setObjectName("input_layer_dd")
        self.input_selector_hlayout.addWidget(self.input_layer_dd)
        self.browse_button = QtWidgets.QToolButton(self.layoutWidget)
        self.browse_button.setObjectName("browse_button")
        self.input_selector_hlayout.addWidget(self.browse_button)
        self.input_selector_hlayout.setStretch(0, 10)
        self.input_selector_hlayout.setStretch(1, 80)
        self.input_selector_hlayout.setStretch(2, 10)

        self.retranslateUi(input_selector_form)
        QtCore.QMetaObject.connectSlotsByName(input_selector_form)

    def retranslateUi(self, input_selector_form):
        _translate = QtCore.QCoreApplication.translate
        input_selector_form.setWindowTitle(_translate("input_selector_form", "Form"))
        self.input_layer_label.setText(_translate("input_selector_form", "Input Layer:"))
        self.browse_button.setText(_translate("input_selector_form", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    input_selector_form = QtWidgets.QWidget()
    ui = Ui_input_selector_form()
    ui.setupUi(input_selector_form)
    input_selector_form.show()
    sys.exit(app.exec_())
