# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\atree\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\shp-feature-selector\ui\selector_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(110, 50, 183, 104))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.state_dd = QtWidgets.QComboBox(self.widget)
        self.state_dd.setObjectName("state_dd")
        self.horizontalLayout_4.addWidget(self.state_dd)
        self.horizontalLayout_4.setStretch(0, 30)
        self.horizontalLayout_4.setStretch(1, 70)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.district_dd = QtWidgets.QComboBox(self.widget)
        self.district_dd.setObjectName("district_dd")
        self.horizontalLayout_3.addWidget(self.district_dd)
        self.horizontalLayout_3.setStretch(0, 30)
        self.horizontalLayout_3.setStretch(1, 70)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.block_dd = QtWidgets.QComboBox(self.widget)
        self.block_dd.setObjectName("block_dd")
        self.horizontalLayout_2.addWidget(self.block_dd)
        self.horizontalLayout_2.setStretch(0, 30)
        self.horizontalLayout_2.setStretch(1, 70)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.village_dd = QtWidgets.QComboBox(self.widget)
        self.village_dd.setObjectName("village_dd")
        self.horizontalLayout.addWidget(self.village_dd)
        self.horizontalLayout.setStretch(0, 30)
        self.horizontalLayout.setStretch(1, 70)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "State:"))
        self.label_3.setText(_translate("Form", "District:"))
        self.label_2.setText(_translate("Form", "Block:"))
        self.label.setText(_translate("Form", "Village:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
